# Generated by Django 4.2.3 on 2023-07-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ques_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
